version: 2
executorType: docker
containerInfo:
  - image: chfast/dev-cpp-gcc:2
stages:
  build:
    workDir: ~/cpp-ethereum
    steps:
      - type: checkout
      - type: shell
        name: "Init submodules"
        command: GIT_SSL_NO_VERIFY=true git submodule update --init
      - type: shell
        name: "Create build dir"
        command: mkdir ~/build
      - type: cache-restore
        key: deps-{{ checksum "cmake/ProjectBoost.cmake" }}
      - type: shell
        name: "Configure"
        pwd: ~/build
        command: cmake ../cpp-ethereum
      - type: shell
        name: "Build"
        pwd: ~/build
        command: make -j4
      - type: cache-save
        key: deps-{{ checksum "cmake/ProjectBoost.cmake" }}
        paths:
          - deps
      - type: shell
        name: "Download tests"
        pwd: ~
        command: |
          pwd
          git clone --depth 1 https://github.com/ethereum/tests
          ls -l tests
      - type: shell
        name: "Test"
        pwd: ~/build
        command: |
          export ETHEREUM_TEST_PATH=~/tests
          pwd
          ls -l $ETHEREUM_TEST_PATH
          test/testeth
