version: 2
executorType: docker
containerInfo:
  - image: chfast/dev-cpp-gcc:2
stages:
  build:
    workDir: ~/cpp-ethereum
    steps:
      - type: checkout
      - type: shell
        name: "Init submodules"
        command: GIT_SSL_NO_VERIFY=true git submodule update --init
      - type: shell
        name: "Create build dir"
        command: mkdir ~/build
      - type: cache-restore
        name: "Restore ccache"
        key: ccache
      - type: cache-restore
        key: deps-{{ checksum "cmake/ProjectBoost.cmake" }}
      - type: shell
        name: "Configure ccache"
        command: |
          ccache -M 0.5
          ccache -s
      - type: shell
        name: "Configure"
        pwd: ~/build
        command: cmake ../cpp-ethereum
      - type: shell
        name: "Build"
        pwd: ~/build
        command: make -j5
      - type: shell
        name: "Prepare cache"
        command: ccache -s
      - type: cache-save
        key: deps-{{ checksum "cmake/ProjectBoost.cmake" }}
        paths:
          - deps
      - type: cache-save
        key: ccache
        paths:
          - ~/.ccache
      - type: shell
        name: "Test"
        pwd: ~/build
        command: |
          export ETHEREUM_TEST_PATH=~/cpp-ethereum/test/jsontests
          pwd
          ls -l $ETHEREUM_TEST_PATH
          test/testeth
