version: 2
executorType: docker
containerInfo:
  - image: ethereum/cpp-build-env
stages:
  build:
    workDir: ~/cpp-ethereum
    steps:
      - type: checkout

      - type: shell
        name: "Init submodules"
        command: git submodule update --init

      - type: shell
        name: "Create build dir"
        command: mkdir ~/build

      - type: cache-restore
        name: "Restore dependencies cache"
        key: deps-2-{{ checksum "cmake/ProjectJsonRpcCpp.cmake" }}

      - type: shell
        name: "Configure"
        pwd: ~/build
        command: cmake ../cpp-ethereum -DCOVERAGE=ON

      - type: shell
        name: "Upload Hunter cache"
        command: |
          cmake --build ~/build --target hunter_upload_cache

      - type: shell
        name: "Build"
        pwd: ~/build
        command: |
          cmake --build . -- -j4

      - type: cache-save
        name: "Save dependencies cache"
        key: deps-2-{{ checksum "cmake/ProjectJsonRpcCpp.cmake" }}
        paths:
          - deps

      - type: cache-restore
        name: "Restore Ethash DAG file"
        key: ethash-dag0

      - type: shell
        name: "Test"
        pwd: ~/build
        command: |
          export ETHEREUM_TEST_PATH=~/cpp-ethereum/test/jsontests
          export TMPDIR=/dev/shm
          test/testeth -t BlockchainTests &
          test/testeth -t StateTestsGeneral &
          test/testeth -t 'KeyStore:Crypto:KeyManagerTests' &
          test/testeth -t '!BlockchainTests:!StateTestsGeneral:!KeyStore:!Crypto:!KeyManagerTests' &
          wait

      - type: cache-save
        name: "Save Ethash DAG file"
        key: ethash-dag0
        paths:
          - ~/.ethash/full-R23-0000000000000000

      - type: shell
        name: "Code coverage"
        pwd: ~/build
        command: |
          cmake --build . --target coverage.data
          bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/d8016a07d67d813f98afdbaf98dc4f46d9806118/codecov) -X fix -f coverage.data
